### ISSUE TITLE
Fails with currency mismatch

### ISSUE THREAD

**Issue by mathiastj** [mathiastj/electricity-price-render#2]
All action runs for today, e.g. https://github.com/mathiastj/electricity-price-render/runs/2355333085?check_suite_focus=true
fail with: 
```
Traceback (most recent call last):
  File "/home/runner/work/electricity-price-render/electricity-price-render/main.py", line 23, in <module>
    hourlyEastDenmarkPrices = prices_spot.hourly(areas=['DK2'])
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nordpool/elspot.py", line 132, in hourly
    return self.fetch(self.HOURLY, end_date, areas)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nordpool/elspot.py", line 128, in fetch
    return self._parse_json(self._fetch_json(data_type, end_date), areas)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/nordpool/elspot.py", line 41, in _parse_json
    raise CurrencyMismatch
nordpool.base.CurrencyMismatch
```

Seems to be explained here: https://github.com/kipe/nordpool/issues/21

It should hopefully fix itself.

**Comment by mathiastj** [comment]
The api output has been fixed: https://github.com/kipe/nordpool/issues/21#issuecomment-820844866
Also seen by the runs completing again: https://github.com/mathiastj/electricity-price-render/actions/runs/753337387
